language: C
sudo: enabled
before_script:
 - ./bootstrap
addons:
  apt:
    update: true
    packages:
      - libssl-dev
  homebrew:
    packages:
      - openssl

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - libsystemd-dev
      script:
        - ./configure --enable-intf-dummy --enable-intf-dbus
        - make
        - sudo make install
    - os: linux
      dist: trusty
      script:
        - ./configure --enable-intf-dummy
        - make
        - sudo make install
    - os: osx
      osx_image: xcode10.2
      script:
        - ./configure --enable-intf-dummy
        - make
        - sudo make install
    - os: windows
      before_install:
        - choco uninstall -y mingw
        - choco upgrade --no-progress -y cygwin
        - ls -l /c/
        - setup-x86.exe -q -P wget -P gcc-g++ -P make -P diffutils -P libmpfr-devel -P libgmp-devel -P libmpc-devel -P openssl-devel
      script:
        - ./configure --enable-intf-lanplus
        - make

